apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rbndjx/agent-assist-sav-backend
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.apiPort }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets