name: Deploy Application
run-name: ${{ github.actor }} is deploying 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: robindijoux/github-action-templates/.github/workflows/kubernetes.yml@main
        with:  
          image: rbndjx/agent-assist-sav-backend:latest
          kubeconfig: ${{ secrets.KUBECONFIG_PROD }}