name: Deploy Application
run-name: ${{ github.actor }} is deploying 🚀
on: [push]
jobs:
  deploy:
    uses: robindijoux/github-action-templates/.github/workflows/kubernetes.yml@main
    with:  
      image: rbndjx/agent-assist-sav-backend:latest
    secrets: inherit